name: VLC Builder

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-vlc:
    name: Build VLC (${{ matrix.target }} - ${{ matrix.track }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: linux-x64
            live555_suffix: linux-64bit
            host: x86_64-linux-gnu
            track: dev
            vlc_ref: master
          - target: linux-x64
            live555_suffix: linux-64bit
            host: x86_64-linux-gnu
            track: stable
            vlc_ref: latest_tag

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

